import './bootstrap';
import './dropdown';
import './cari-kerja';
import './rating';
import '../css/master.css';
import '../css/search.css';
import '../css/cari-kerja.css';
import '../css/beranda.css';
import '../css/postwork.css';
